### PR TITLE
.flow Esperanto translation

### PR DESCRIPTION
**Pull request by Leo9nine9**
by leo9

### CODE REVIEW

**Comment by Mimigris** [comment]
Just checked the translation:

Map0003:
- The line for getting the Broom effect is too long to be displayed entirely

Map0008, 0012, 0127, 0133, 0134, 0190, 0193, 0214, 0288:
- The text is not centered

RPG_RT.ldb:
- Malveraj Instrukcioj de Ludo has its name too long to be displayed

Any reason to have touched the System files this way? This doesn't really make sense to do such an edit which doesn't seem to be a translation (also, extra pixel on the 2 of FCシムテム)
Map0232, Map0257 can be removed due to not containing text that has to be translated
What's the difference between effects ending in o or not? I see they end in o in the Debug Room and in some descriptions, but only in some, is that intended?

**Comment by Leo9nine9** [comment]
Now centred the text on those files and fixed the Broom effect.
I don't think that Malveraj Instrukcioj de Ludo is text that can ever appear in game, but I have shorted it anyway.
I took the System images from the Italian translation (which I consulted at various points during my translation), just because I prefer it saying "flow" when entering the dream world instead of the Japanese, but I recognise that this is not an Esperanto translation, and given that the English translation does not translate this, I will leave it untranslated as well.

About the effects ending in -o. Nouns ending in -on in Esperanto mark that they are the object of a verb. So the name of Broom is "Balailo", but when it is the object of a verb, it takes an -n ending, e.g. "Balailon Akiris". So it is intentional.

**Comment by Leo9nine9** [comment]
Thank you for doing such thorough checks of the translation!

**Comment by Mimigris** [comment]
Looks all good to me now! 👍

**Pull request merged**
