### PR TITLE
[She Awaits] Russian Translation

### PR DESCRIPTION
**Pull request by CharaTroll**
* Russian Translation for She Awaits

* Created by TrolChelavi, tested by Kowinski

Thanks for attention!

### CODE REVIEW

**Comment by CharaTroll** [comment]
Tasks 2 and 3 fixed. Task 1 should be fixed, if I did everything right.

**Comment by Mimigris** [comment]
Tasks 2 and 3 seem to be fixed, indeed. For the task 1, I have no idea how and why it occurs but your current file displays incorrect graphics when called (Maybe it is the same as https://github.com/EasyRPG/Player/issues/2984 ?). Here's a fixed version, download it and replace it by yours, this should hopefully fix this last issue.
ani-effectandcoin

**Comment by CharaTroll** [comment]
File has been replaced. Thanks!

**Comment by Mimigris** [comment]
Should be all good now! 👍

**Pull request merged**
