### PR TITLE
Edit some files and add file to flow Korean translate

### PR DESCRIPTION
**Pull request by ASDJKL1244**

### CODE REVIEW

**Comment by Flashfyre** [comment]
It would have been better if you made the restored PR 20 separate, I still have to eventually go through and improve the translation fluency for the 2kki one.

**Comment by ASDJKL1244** [comment]
> It would have been better if you made the restored PR 20 separate, I still have to eventually go through and improve the translation fluency for the 2kki one.

Okay. Then I will post Korean and English translation separately

**Comment by ASDJKL1244** [comment]
Should I leave the picture as it is, or should I divide this as well? Is there a grammatical error in the picture?

**Comment by ASDJKL1244** [comment]
Delete complete

**Comment by ASDJKL1244** [comment]
Added Wavy up Translation

**Pull request merged**
