### PR TITLE
Add more

### PR DESCRIPTION
**Pull request by lychees**

### CODE REVIEW

**Comment by Flashfyre** [comment]
Please let me know when this PR is finished and ready to be merged, if not already

**Comment by lychees** [comment]
> Please let me know when this PR is finished and ready to be merged, if not already

I think we could merge this PR at this moment.
The only remaining work is FC world, but people hardly go there and there is too much picture around it.
It is very easy to miss one picture or have a mistake due to the terribile file name in English translation.

I think I need to write a piece of script to replace them all so that we could easily verify the correctness.

**Comment by Flashfyre** [comment]
Can we change 'ch' to 'zh' for consistency? It won't automatically infer it from Simplified Chinese UI language otherwise.

**Comment by lychees** [comment]
> Can we change 'ch' to 'zh' for consistency? It won't automatically infer it from Simplified Chinese UI language otherwise.

Done.

**Review by Flashfyre — CHANGES_REQUESTED** [review]
Also need 'sp' renamed to 'es'

**Comment by Flashfyre** [comment]
'jp' also needs to be 'ja' but I will fix that

**Pull request merged**
