### PR TITLE
Edit Yumenikki Korean Translate

### PR DESCRIPTION
**Pull request by Aronako**
The translation was not displayed properly, so I modified it.

### CODE REVIEW

**Comment by Aronako** [comment]
Some files have broken characters I'll edit it and upload it again. I'm sorry again.

**Comment by Aronako** [comment]
(I've checked that it's working properly.)

**Review by Flashfyre — APPROVED** [review]

**Comment by Flashfyre** [comment]
You have some conflicts here from the .flow translation. Can you fix them?

**Comment by Aronako** [comment]
> You have some conflicts here from the .flow translation. Can you fix them? I probably should have merged this one first.

I corrected it. Could you check again if there is any conflict?

**Comment by Flashfyre** [comment]
Doesn't look right. If you look at files changed it appears to affect translations other than this one. Can you find a way to fix this?

**Comment by Aronako** [comment]
> Doesn't look right. If you look at files changed it appears to affect translations other than this one. Can you find a way to fix this?

I'm sorry. I've tried many things, but it keeps affecting the translation of deep dreams into Russian.
I also don't want anyone else's translation to go wrong, so I'll close this pull request, add a new yumenikki translation file on the already applied patch 2, and apply for pull request again.
It's my fault that I made another patch before you applied it.

**Pull request closed without merging**
