### PR TITLE
Partial Yume 2kki Ru Translation

### PR DESCRIPTION
**Pull request by Fonvight**
Done:
* Effects
* Menu Themes
* Drawers (Real Room, Dream Room)
* PC (Both UI and Sound Rooms; Except Debug menus)
* Bookshelf
* Xylophone

At least partially:
* Mini-games (E.g. Some phrases in WavyUp left untranslated on purpose; MiniGameB should be finished)
* Dev Room (Don't have a save file to test properly; Only the Entrance NPC and 20)
* Time Trial mode Stopwatch (Questionable: menu20 and menu21)
* Library (Controls, Nikki and heart256)

Not even touched:
* Most of the Library Books (A lot of work should be done)
* Debug Room (Inaccessible in Normal game)
* Something else I've possibly forgotten.

Seems untranslatable:
* Word World, as well as some other locations made of letters\words (Requires Map Adjustment from editor)
* One of the Credits Sequence (See "Word World")

Notes:
* Changed a bit the "Effect get" splash, since otherwise the text overlaps the stars.
* Main Menu Title screen left practically identical to the one found in Original game, except the "Work in progress" phrase in the corner
* As for now, the `F o n t` problem seems unsolvable by the means accessible without the patching. Because of this, a lot of adjustments has been made. However, where possible (Mostly in the Pictures), the Text are drawn without this issue.

### CODE REVIEW

**Review by Mimigris — COMMENTED** [review]
Have you checked if the GB Menu was displaying correctly if you don't have effects? I know it has been a general issue with translations, so I'm checking if it work as intended.
Here's an exemple with the Korean translation of what can be wrong.

A way to get to GB World without effects is:
Heart World -> The Deciding Street -> Dizzy Spirals World -> Slave Robotic Tunnel -> Hand Game Pond -> GB World

You will hand up in the Green version, and by going further you will find the White version.

**Comment by Fonvight** [comment]
> Have you checked if the GB Menu was displaying correctly if you don't have effects? I know it has been a general issue with translations, so I'm checking if it work as intended. 

Just went to check this in both versions: Seems to work just fine.

Green Menu
White Menu

Thanks for the mention about Issue possibility. 
Also, seem like the non-transparent space outside the frames on the GB pictures are intended, since its there even in Original game.

**Comment by Mimigris** [comment]
Just done a small check since it was also a problem in the french translation, but some texts are cut in the Sound Room, and some numbers input get delayed to a next page if the text is too long (like 4 lines just before the number input).
2kkiru1
2kkiru2
You may have to check a lot of text of the Sound Room (Map0620) and of the computer menu (Map0002) since they are the texts who are the most likely cut due to not having enough space.

**Comment by Mimigris** [comment]
> * Main Menu Title screen left practically identical to the one found in Original game, except the "Work in progress" phrase in the corner
Is it intended that the Title screen font of "Yume 2kki" is a little bit different than the one of the Japanese version ?

**Comment by Fonvight** [comment]
> Is it intended that the Title screen font of "Yume 2kki" is a little bit different than the one of the Japanese version ?

Possibly, the picture either changed in-game, or somehow was corrupted while I was copying the file from backup. Anyway, updated to match the current one.

> You may have to check a lot of text of the Sound Room (Map0620) and of the computer menu (Map0002) since they are the texts who are the most likely cut due to not having enough space.

Seems like I've done with it by the most, however, since I've not tested everything properly, some consistency of the menus has been lost.

>  I've also found two cuts texts linked to the Time Trial (Map0008) and to the Time Trial warning message when saving (Map0002)

Thanks! Fixed.

**Comment by Mimigris** [comment]
Just checked the Map1521, nothing to say it work as intended,
ゆめ2っき - EasyRPG Player 10_08_2022 19_49_58
so your translation should be ready to go 👍 !

**Comment by Ghabry** [comment]
The full width cyrillic font is a shortcoming of how easyrpg player handles translations btw.

There is a fix in the works that fixes the rendering.

**Comment by Mimigris** [comment]
> The full width cyrillic font is a shortcoming of how easyrpg player handles translations btw. The normal cyrillic font is only half the width.
> 
> There is a fix in the works that fixes the rendering.

That could be interesting for future translations, but it will need to recenter texts that requires specific numbers of space so currently using it for a translation will require some rework.

**Pull request merged**
